# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data',sep = '\s+')

In [4]:
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [5]:
data['date_int'] = data.Yr*10000+data.Mo*100+data.Dy+19000000
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date_int
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,19610101
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,19610102
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,19610103
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,19610104
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,19610105

In [6]:
data['date'] = pd.to_datetime(data.date_int,format = '%Y%m%d')

In [7]:
del data['date_int']

In [8]:
data.drop(['Yr','Mo','Dy'],axis=1,inplace=True)

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [9]:
data.set_index('date',inplace=True)

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [10]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [26]:
data.notna().sum()

RPT    6574
VAL    6574
ROS    6574
KIL    6574
SHA    6574
BIR    6574
DUB    6574
CLA    6574
MUL    6574
CLO    6574
BEL    6574
MAL    6574
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [12]:
data.fillna(0,inplace=True)
#均值填充需要一列一列来吗

In [13]:
data.values.mean()

10.223864592840481

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [14]:
data.describe()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000,6574.000000
mean,12.351704,10.639457,11.656979,6.301672,10.452653,7.092254,9.792872,8.492469,8.489714,8.706007,13.121007,15.589588
std,5.628245,5.271060,5.011816,3.608631,4.938742,3.968683,4.980816,4.501204,4.169870,4.504892,5.835037,6.708793
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.130000,0.000000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.170000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [15]:
data.T.describe()

date,1961-01-01,1961-01-02,1961-01-03,1961-01-04,1961-01-05,1961-01-06,1961-01-07,1961-01-08,1961-01-09,1961-01-10,...,1978-12-22,1978-12-23,1978-12-24,1978-12-25,1978-12-26,1978-12-27,1978-12-28,1978-12-29,1978-12-30,1978-12-31
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,...,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,11.933333,10.391667,10.671667,6.619167,10.630000,8.240000,10.385000,10.487500,9.897500,10.47750,...,7.000833,15.613333,10.823333,5.729167,6.523333,16.708333,15.150000,14.890000,15.367500,15.402500
std,4.614681,4.467057,4.859876,3.198126,2.445356,2.998063,3.072114,3.547237,2.905954,3.44261,...,3.237337,3.850840,7.195039,3.583263,4.304510,7.868076,9.687857,5.756836,5.540437,5.702483
min,0.000000,0.000000,0.000000,1.790000,6.170000,4.420000,4.960000,5.910000,4.750000,6.54000,...,2.460000,9.500000,4.790000,0.750000,1.960000,8.080000,5.000000,8.710000,9.130000,9.590000
25%,10.155000,9.170000,8.292500,4.570000,9.807500,6.345000,8.237500,7.620000,7.977500,8.48750,...,5.077500,12.987500,5.840000,4.102500,3.070000,13.802500,9.095000,10.477500,12.375000,11.530000
50%,12.875000,10.435000,11.210000,5.855000,11.170000,7.810000,9.395000,9.685000,10.065000,9.35500,...,6.795000,15.395000,10.040000,5.230000,4.540000,15.025000,13.895000,14.210000,13.455000,12.080000
75%,14.980000,12.922500,12.720000,9.117500,12.170000,10.137500,13.572500,11.792500,11.267500,11.52250,...,8.765000,17.495000,11.970000,7.365000,10.722500,17.302500,16.700000,17.035000,18.185000,19.520000
max,18.500000,17.540000,18.500000,11.750000,13.330000,13.210000,14.290000,16.620000,15.370000,19.50000,...,13.080000,22.210000,31.710000,13.960000,13.830000,40.080000,41.460000,29.580000,28.790000,27.290000

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [16]:
import datetime

In [17]:
data[data.index.month==1].mean()

RPT    14.820717
VAL    12.891416
ROS    13.299624
KIL     7.199498
SHA    11.625914
BIR     8.054839
DUB    11.819355
CLA     9.495000
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [21]:
data.groupby(data.index.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961,12.131096,10.266712,11.300110,6.881973,10.822137,7.729726,9.653918,8.810247,8.576575,9.808630,13.502795,13.568329
1962,12.213370,10.110438,11.732712,6.941370,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.284712
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [22]:
data.groupby(data.index.month).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1,14.820717,12.891416,13.299624,7.199498,11.625914,8.054839,11.819355,9.495000,9.543208,10.053566,14.550520,18.028763
2,13.710906,12.111122,12.853780,6.915079,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142
3,13.111523,11.505842,12.648118,7.252885,11.554516,7.959409,11.310179,9.635896,9.665556,10.096953,13.810609,16.848710
4,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611
5,11.724032,10.127437,11.550394,6.296183,10.224301,6.942061,8.781971,8.452903,8.040806,8.524857,12.767258,13.736039
6,10.431963,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.838000
7,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.829444,7.262760,7.544480,7.321416,11.676505,12.800789
8,10.195108,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,6.990233,11.110090,12.543423
9,11.458519,9.962519,10.736963,5.604778,9.766315,6.566222,8.609722,7.731333,7.610556,7.689278,12.686389,14.761963
10,12.637921,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.332222,8.850376,14.155323,16.697151
11,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.794833,8.427167,8.604000,8.943167,13.815741,18.114185
12,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599

### Step 14. Downsample the record to a weekly frequency for each location.

In [23]:
data.groupby(data.index.week).mean()

E:\python3.6\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  """Entry point for launching an IPython kernel.

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1,13.920000,11.617937,12.853016,6.617302,10.473175,7.578492,11.623651,9.051190,9.272222,9.870635,14.241746,18.249841
2,15.549921,13.359524,14.016349,7.307698,12.183810,8.170238,11.934365,9.502460,9.428095,9.798175,14.494603,17.623413
3,14.950159,13.281349,13.166825,7.060794,11.864286,8.320238,11.856905,9.696825,9.597619,10.169444,14.578254,17.981190
4,15.120952,13.575317,13.554524,7.698413,12.110079,8.235159,11.732857,9.854048,9.822302,10.352063,14.892222,18.337381
5,14.559127,12.853413,13.070794,7.400952,11.823730,8.165397,11.995714,9.682381,9.854286,10.196111,14.667381,17.702222
6,13.203730,11.508492,12.142619,6.469127,11.025476,7.166746,11.115317,8.894206,9.323413,9.298175,13.903254,17.921587
7,14.517460,12.681349,13.219524,7.091429,12.141032,7.906190,11.390238,9.749524,9.417778,9.605476,13.776667,17.130159
8,13.422857,11.822937,13.367381,7.085714,11.480635,7.729683,11.329048,9.329762,9.247063,9.541984,13.132302,16.882540
9,12.660079,11.837460,12.527222,6.620000,10.937143,7.457778,10.622778,9.387778,8.793810,9.611508,13.724048,16.470317
10,13.419365,11.758095,13.151667,7.317063,11.477143,7.965397,10.751111,9.151825,9.367302,9.761429,13.055000,16.047381
11,13.597143,11.495079,13.032698,7.446270,11.689206,7.990238,11.444365,10.038968,9.783730,10.398730,13.823968,17.193730
12,13.006825,11.621032,12.579048,7.390476,11.850476,8.288095,12.008413,10.136746,10.176270,10.259048,14.389524,17.859365
13,12.772540,11.076349,12.104444,7.328016,11.664286,8.042063,11.306587,9.494365,9.898571,10.038571,14.241667,16.486508
14,13.903968,11.025238,14.149286,7.798968,11.482857,8.006905,11.525238,9.579921,9.894762,9.948175,13.386270,16.691349
15,12.599444,9.966667,11.654286,6.758175,10.642540,7.377778,10.677143,9.328413,9.248333,9.338413,12.842460,15.900476
16,12.753968,11.111587,11.966587,7.110000,10.983730,7.660794,9.981905,8.763571,8.802063,9.326905,12.472857,14.229524
17,10.966349,9.647698,11.272619,6.019286,9.627857,6.687063,8.870714,8.091825,7.836032,8.238333,11.971667,13.097460
18,12.897222,11.095079,11.256825,6.745794,11.035952,7.405238,9.318730,8.674206,8.340952,8.952857,12.928968,14.523810
19,13.061429,11.275159,12.630397,7.005238,10.944683,7.559603,9.547937,9.111349,8.604683,9.243254,13.721984,14.288016
20,11.338571,9.691667,11.566746,6.195238,9.967937,6.811429,8.732857,8.495317,7.984365,8.507540,12.740952,13.859286
21,11.282698,9.673889,11.223968,5.928254,10.051905,6.730476,8.435397,8.150556,7.871587,8.278413,12.536270,13.626825
22,9.673333,8.264683,10.382302,5.195397,8.696825,5.802063,7.275873,7.533016,7.120873,7.247222,11.238810,11.770317
23,10.092143,8.980556,10.030476,5.304048,8.882143,5.816825,7.420952,7.387857,7.031587,7.173810,11.605635,12.395476
24,10.131905,8.741984,10.518254,5.498492,8.997381,6.189762,7.320317,7.597143,7.172857,7.259524,11.835873,12.041270
25,11.680238,9.898016,10.730397,6.294444,11.030397,7.410952,9.410238,8.822698,8.728016,8.677063,13.494762,14.329841
26,9.956349,8.770635,10.113333,5.798492,9.680159,6.474603,8.226032,7.920556,7.906270,7.937778,12.462222,12.890714
27,9.991984,7.916984,8.741032,5.276825,8.998175,5.852302,7.755635,7.182143,7.662143,7.451349,11.582857,13.096984
28,9.962143,8.272619,9.651349,5.461270,9.344206,5.951111,7.937857,7.341746,7.671905,7.267063,11.450159,12.932460
29,10.281746,8.422063,9.755079,5.672778,9.766667,6.300238,8.277619,7.568175,7.725952,7.616349,12.021667,12.880476
30,9.760397,8.211984,9.181587,5.195476,8.920873,5.657222,7.566905,6.904603,7.078571,7.010317,11.410794,12.279683
31,9.721984,8.218571,9.585556,5.078651,8.940397,5.692857,7.470397,6.646746,7.039206,6.615556,11.020317,12.348492
32,10.121667,8.669683,9.357619,5.524206,9.143492,6.091984,7.518413,6.896190,7.409365,7.001825,11.154365,12.746587
33,10.213254,8.000476,10.086667,5.169127,8.638413,5.652619,7.635635,6.591746,7.033413,6.502460,10.647222,11.225873
34,10.675556,9.065317,10.466190,5.380635,9.343651,6.275317,8.164603,7.503889,7.753730,7.779206,11.881667,13.764762
35,10.378571,8.525476,10.496746,5.398571,8.739444,5.938968,8.088889,6.907857,7.063016,7.213175,11.606825,13.390873
36,10.764365,9.296190,9.931270,5.387381,9.245873,6.353810,8.314603,7.012857,7.449762,7.221905,11.597619,13.754921
37,11.371190,9.722857,10.963889,5.638810,9.603968,6.646587,8.698492,7.704841,7.532143,7.645952,12.658968,14.827540
38,9.929524,8.863095,10.163968,4.426667,8.346190,5.408175,7.285079,6.671270,6.387381,6.423095,11.394127,13.094921
39,13.960635,12.263810,11.787302,6.898095,11.971032,7.882540,10.012619,9.489206,8.933413,9.402540,14.980000,16.928095
40,12.199841,10.619127,11.392698,5.854048,10.308175,6.841508,9.301905,8.581111,8.561667,8.519524,13.326429,15.758095
41,12.163492,10.581508,11.316190,5.468889,9.998254,6.667460,8.667778,8.279444,7.782540,8.176825,13.550952,15.663571
42,12.777460,10.966587,11.381667,6.349048,10.716032,7.526032,9.941349,8.802222,8.460873,9.039286,14.088175,17.116111
43,13.358651,11.915238,11.888095,6.554286,11.363571,7.769524,10.170873,9.458889,8.855000,9.800873,16.055873,18.580952
44,13.338254,11.704444,12.378889,6.522857,10.578651,7.346746,9.806349,9.072063,8.721190,9.427222,14.410079,18.089048
45,13.292857,11.758968,12.691984,6.169048,10.683333,7.268968,10.657222,8.751429,8.747937,8.962302,13.990317,18.065794
46,14.081746,12.423571,13.064365,6.937619,11.509206,7.785794,11.578730,8.881587,9.058968,9.487302,14.063889,19.360873
47,11.731508,10.361667,11.107698,5.413968,9.200952,6.172540,9.991984,7.322222,7.690397,7.933095,12.399762,16.473254
48,13.843413,12.230159,12.048016,6.364762,11.060238,7.585952,11.483254,8.639048,8.944365,9.121190,14.481111,18.234365
49,14.685000,12.947222,12.649286,7.161984,11.855635,8.497937,12.840952,9.561905,10.218492,9.994524,15.140397,19.625714
50,14.462619,12.462619,12.750714,7.041349,11.603095,8.226508,11.780714,9.310635,9.301508,9.842698,14.716905,18.242937
51,13.639921,11.697619,12.501667,5.991270,10.541667,7.275159,10.301667,8.462619,8.438730,8.687937,13.298889,17.182063
52,14.469134,11.692283,14.210000,7.018189,10.771417,7.379213,12.011969,9.121811,9.665197,9.677953,13.549055,19.183228
53,12.694286,9.451905,13.526190,5.343810,8.040476,5.884286,10.366190,5.556190,6.954286,7.820952,11.028095,17.103810

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [24]:
(data.groupby(data.index.week).mean()).describe()

E:\python3.6\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  """Entry point for launching an IPython kernel.

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,12.356773,10.620627,11.685987,6.286504,10.414678,7.073218,9.801554,8.446207,8.465396,8.691945,13.088035,15.612858
std,1.727099,1.629881,1.407177,0.838192,1.173851,0.889344,1.641991,1.093659,1.014636,1.168109,1.311990,2.358703
min,9.673333,7.916984,8.741032,4.426667,8.040476,5.408175,7.275873,5.556190,6.387381,6.423095,10.647222,11.225873
25%,10.675556,9.065317,10.496746,5.468889,9.343651,6.275317,8.277619,7.533016,7.671905,7.645952,11.881667,13.390873
50%,12.753968,11.025238,11.787302,6.349048,10.642540,7.346746,9.981905,8.751429,8.604683,8.962302,13.298889,16.047381
75%,13.639921,11.758968,12.750714,7.041349,11.480635,7.785794,11.390238,9.329762,9.301508,9.677953,14.088175,17.702222
max,15.549921,13.575317,14.210000,7.798968,12.183810,8.497937,12.840952,10.136746,10.218492,10.398730,16.055873,19.625714